Use correct format specifier for time_t
use %jd instead of %ld to print variable of time_t type otherwise
on 32 bit system:

src/thd_gddv.cpp:457:41: error: format '%ld' expects argument of type 'long int', but argument 11 has type 'time_t' {aka 'long long int'} [-Werror=format=]
src/thd_gddv.cpp:457:41: error: format '%ld' expects argument of type 'long int', but argument 13 has type 'time_t' {aka 'long long int'} [-Werror=format=]

Signed-off-by: Yogesh Tyagi <yogesh.tyagi@intel.com>