thd_gddv: fix building on 32-bit systems
Fix the error caused by type mismatch:

src/thd_gddv.cpp: In member function 'int cthd_gddv::evaluate_condition(condition&)':
src/thd_gddv.cpp:1721:39: error: format '%ld' expects argument of type 'long int', but argument 4 has type 'time_t' {aka 'long long int'} [-Werror=format=]

Signed-off-by: Dmitry Baryshkov <dmitry.baryshkov@oss.qualcomm.com>